apiVersion: v1 
kind: Service 
metadata:
  name: kicad-service 
spec: 
  type: LoadBalancer
  selector:
    app: kicad
  ports:
    - port: 80
      targetPort: 8051

#kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/cloud/deploy.yaml
