apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kicad-service-{{.Release.Name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
        - path: /kicad/?(.*)
          backend:
             serviceName: kicad-service-{{.Release.Name}}
             servicePort: {{.Values.service.port}}