apiVersion: apps/v1
kind: Deployment
metadata:
  name: kicad-deployment-{{.Release.Name}}
  labels:
    app: kicad-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: kicad-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: kicad-{{.Release.Name}}
    spec:
      containers:
      - name: kicad-{{.Release.Name}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}